Feat support external traffic policy [WIP]
kubernetes/kompose pull request #1544
Opened 2022-12-01 14:49 UTC by AhmedGrati

2022-12-02 09:30 UTC, ZakariaNaaija commented
Hi @AhmedGrati,
Thanks for handling the issue I have mentioned.

> Since the externalTrafficPolicy is only specified when we have a Service of type LoadBalancer, we will output a warning message when the user specifies another type of Service.

externalTrafficPolicy can be used along with a service of type NodePort.  
> Local preserves the client source IP and avoids a second hop for LoadBalancer and NodePort type Services, but risks potentially imbalanced traffic spreading.

[Source](https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip)

2022-12-02 09:36 UTC, AhmedGrati commented
> Hi @AhmedGrati, Thanks for handling the issue I have mentioned.
> 
> > Since the externalTrafficPolicy is only specified when we have a Service of type LoadBalancer, we will output a warning message when the user specifies another type of Service.
> 
> externalTrafficPolicy can be used along with a service of type NodePort.
> 
> > Local preserves the client source IP and avoids a second hop for LoadBalancer and NodePort type Services, but risks potentially imbalanced traffic spreading.
> 
> [Source](https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip)

Thank you for raising it, much appreciated. I will update it.

2023-01-08 08:43 UTC, mrsangjunboon2018 commented
FUCK!

2023-02-08 20:51 UTC, cdrage commented
This will need a huge rebase, sorry for the work @AhmedGrati !

2023-02-09 22:36 UTC, AhmedGrati commented
@cdrage It's ready to be reviewed.

2023-02-10 15:45 UTC, cdrage reviewed
The code LGTM but can you add some documentation as well for the user guide / under labels as this is a new label?

2023-02-10 15:58 UTC, cdrage reviewed
Just sayin', these tests are GREAT and thank you so much for always covering it all 💯 💯 💯

2023-02-11 11:28 UTC, AhmedGrati commented
> The code LGTM but can you add some documentation as well for the user guide / under labels as this is a new label?

Yes makes sense 👌. Done!

2023-02-12 13:31 UTC, cdrage commented
Thank you! Can you show all the options? I think it's cluster, local and blank right?

2023-02-13 13:35 UTC, cdrage requested changes

2023-02-13 13:35 UTC, cdrage commented on docs/user-guide.md
> +| kompose.service.external-traffic-policy: local       | kubernetes service external traffic policy                                                   |
```suggestion
| kompose.service.external-traffic-policy       | 'cluster', 'local', ''                                                   |
```

Let's just do this for now until we update the documentation on user guide. It's a bit of a mess right now to understand / comprehend and I plan to work on this, this month.

2023-02-13 17:14 UTC, cdrage approved these changes

2023-02-13 17:15 UTC, cdrage commented
/lgtm

2023-02-13 17:15 UTC, merged