feat: adding support for --profile cmd option
kubernetes/kompose pull request #1709
Opened 2023-09-17 15:42 UTC by axel7083

#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kompose/issues/1708

#### Special notes for your reviewer:

2023-09-21 19:00 UTC, cdrage commented
The code LGTM and implementation! But you'll have to add a test if that's okay for it to be all merged in:)

2023-09-21 20:11 UTC, axel7083 commented
> The code LGTM and implementation! But you'll have to add a test if that's okay for it to be all merged in :)

I've added a test in the client. To do so, I added an example of docker-compose with some profile, and using the tool, I ensure it matches the expected output.

2023-09-25 23:59 UTC, cdrage requested changes
One TINNYYYY change (no period at end of sentence and little bit of grammar change), but otherwise LGTM!

2023-09-25 23:59 UTC, cdrage commented on cmd/convert.go
> +	convertCmd.Flags().StringArrayVar(&ConvertProfiles, "profile", []string{}, `Specify the profile to use, can use multiple.`)
```suggestion
	convertCmd.Flags().StringArrayVar(&ConvertProfiles, "profile", []string{}, `Specify the profile to use, can use multiple profiles`)
```

2023-09-26 13:44 UTC, cdrage approved these changes

2023-09-26 13:44 UTC, cdrage commented
/approve

2023-09-26 13:44 UTC, cdrage commented
/lgtm

2023-09-26 13:45 UTC, merged