Feature 1635 - customizing service name with prefix, flag --prefix (-x)
kubernetes/kompose pull request #1833
Opened 2024-02-23 23:48 UTC by sosan

#### What type of PR is this?

/kind feature 

#### What this PR does / why we need it:
The --prefix flag serves the purpose of allowing users to specify prefixes to be added to the names of services

#### Which issue(s) this PR fixes:

Feature #1635

#### Special notes for your reviewer:
I haven't had time to document the --prefix flag
documentation will be cooming soon in the following commits.

2024-02-29 11:42 UTC, TessaIO reviewed
Thanks for the patch @sosan. I left some comments below.

2024-03-01 20:22 UTC, cdrage commented
@TessaIO shouldn't we have this as a label param instead? or do you think CLI parameter would be fine?

2024-03-01 20:28 UTC, TessaIO commented
> @TessaIO shouldn't we have this as a label instead? or do you think CLI parameter would be fine?

That's actually true if we want to offer users flexibility to specify per-service prefixes that's the option to go (I mean labels here).

2024-03-01 20:44 UTC, cdrage commented
> > @TessaIO shouldn't we have this as a label instead? or do you think CLI parameter would be fine?
> 
> That's actually true if we want to offer users flexibility to specify per-service prefixes that's the option to go (I mean labels here). wdyt @sosan?

Yeah just thinking about it again, I think I'm good for terminal / cli based prefixes being added, we could always customize the name individually via labels instead.

2024-03-05 19:13 UTC, sosan commented on pkg/transformer/kubernetes/k8sutils_test.go
> +			name: "-Testing-Bad-",
done

2024-03-05 19:13 UTC, sosan commented on pkg/transformer/kubernetes/k8sutils_test.go
> +			name: "-TEST_FAIL",
done

2024-03-05 19:14 UTC, sosan commented on pkg/transformer/kubernetes/k8sutils.go
> +	return prefix
done

2024-03-05 19:14 UTC, sosan commented on pkg/transformer/kubernetes/k8sutils.go
> +func appendPrefixName(komposeObject *kobject.KomposeObject, prefixArray []string) *kobject.KomposeObject {
done

2024-03-05 19:14 UTC, sosan commented on cmd/root.go
> +	RootCmd.PersistentFlags().StringSliceVarP(&GlobalPrefixAdd, "prefix", "x", []string{}, "Add prefix in name services")
done

2024-03-05 19:14 UTC, sosan commented on pkg/transformer/kubernetes/k8sutils_test.go
> +			name: "-TEST_FAIL-",
done

2024-03-05 19:18 UTC, sosan commented
Updated cli

Sounds like a good idea to me. That way, we can fine-tune the names individually using labels

2024-03-05 21:26 UTC, TessaIO reviewed
Small comments are left below.

2024-03-05 21:26 UTC, TessaIO commented on pkg/transformer/kubernetes/k8sutils.go
> +	return prefix
```suggestion
	return strings.Trim(FormatResourceName(prefix), "-")
```

2024-03-05 21:26 UTC, TessaIO commented on pkg/app/app.go
> +
```suggestion
```

2024-03-05 22:39 UTC, sosan commented on pkg/app/app.go
> +
updated

2024-03-06 09:33 UTC, TessaIO approved these changes
LGTM! Leaving final approve to @cdrage

2024-03-21 12:16 UTC, cdrage requested changes
One small change requested

2024-03-21 12:16 UTC, cdrage commented on cmd/root.go
> +	RootCmd.PersistentFlags().StringVarP(&GlobalPrefixAdd, "prefix", "x", "", "Add prefix in name services")
```suggestion
	RootCmd.PersistentFlags().StringVarP(&GlobalPrefixAdd, "prefix", "x", "", "Adds a custom prefix to service names")
```

2024-04-02 12:19 UTC, cdrage requested changes
If we are going to add prefix, we should also add suffix...

I do not believe we should have `-x` either. Prefix and suffix should honestly be fixed after generation. I am not opposed to having this merged in as there is an issue opened for it, but we should also add suffix too.

2024-04-02 13:41 UTC, sosan commented
> we should also add suffix too.

ok, roger that

2024-04-18 14:16 UTC, TessaIO commented
ping @cdrage

2024-04-19 12:20 UTC, cdrage requested changes

2024-04-25 16:18 UTC, sosan commented on cmd/convert.go
> +	convertCmd.Flags().StringVarP(&GlobalPrefixAdd, "prefix", "x", "", "Adds a custom prefix to service names")
Sure. Add a suffix with flag? Labels?

2024-04-25 16:33 UTC, cdrage commented on cmd/convert.go
> +	convertCmd.Flags().StringVarP(&GlobalPrefixAdd, "prefix", "x", "", "Adds a custom prefix to service names")
Just flag like how you did it with suffix

2024-04-25 16:49 UTC, cdrage commented
Hey sorry @sosan for some reason I didn't realize that we reached a conclusion on https://github.com/kubernetes/kompose/issues/1635#issuecomment-2031874480 that we should actually close this PR, and I apologize the work you've put into this back and forth.

Going forward I do not think we should be adding too many suffix and prefix / name customizations unless it's "generic", if someone wants to edit the entire `-tcp` suffix, they could do it with a sed / ctrl +f / ctrl + replace after converting.

There's too much work and labels / parameters to be added to make something small like this happen.

2024-04-25 16:49 UTC, closed without merging