adds a label for initContainers, test and user-guide
kubernetes/kompose pull request #1840
Opened 2024-03-13 19:46 UTC by sosan

#### What type of PR is this?

/kind feature 
#### What this PR does / why we need it:
Add label for initContainers
for example: 
kompose.init-contaners.name: "init-service"
kompose.init-contaners.image: "busybox:1.28"
kompose.init-contaners.command: "['sh', '-c', 'until nslookup myservice.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done']"

#### Which issue(s) this PR fixes:

Feature #1772

#### Special notes for your reviewer:

2024-03-16 21:15 UTC, TessaIO requested changes
@sosan Thanks for the PR. I put some comments below, and I'll do another round of review once my comments are addressed. One thing to add, can you add some e2e tests for this?

2024-03-16 21:15 UTC, TessaIO commented on docs/user-guide.md
> +version: '2'
Let's refer to new versions
```suggestion
version: '3'
```

2024-03-16 21:15 UTC, TessaIO commented on docs/user-guide.md
> +
small nit here:
```suggestion
```

2024-03-16 21:15 UTC, TessaIO commented on docs/user-guide.md
> +version: '2'
same as above

2024-03-16 21:15 UTC, TessaIO commented on docs/user-guide.md
> +version: '2'
same as above

2024-03-16 21:15 UTC, TessaIO commented on pkg/transformer/kubernetes/k8sutils.go
> +// https://kubernetes.io/docs/concepts/workloads/pods/init-containers/
Let's conform with the Golang comments style here. I suggest:
```suggestion
// fillInitContainers looks for an initContainer resources and its passed as labels
// if there is no image, it does not fill the initContainer
// https://kubernetes.io/docs/concepts/workloads/pods/init-containers/
```

2024-03-16 21:15 UTC, TessaIO commented on pkg/transformer/kubernetes/k8sutils.go
> +// bundle exec thin -p 3000
Same as above:
```suggestion
// parseContainerCommandsFromStr parses a string containing comma-separated commands
// returns a slice of strings or a single command and
// example:
// [ "bundle", "exec", "thin", "-p", "3000" ]
//
// example:
// bundle exec thin -p 3000
```

2024-03-17 23:52 UTC, sosan commented
> @sosan Thanks for the PR. I put some comments below, and I'll do another round of review once my comments are addressed. One thing to add, can you add some e2e tests for this?

suggestions fixed
added test e2e for initcontainer

```
===> Starting test <===
convert::expect_success_and_warning: Running: 'kompose -f /home/runner/work/kompose/kompose/script/test/fixtures/initcontainer/compose.yaml convert --stdout --with-kompose-annotation=false' expected_output: '/home/runner/work/kompose/kompose/script/test/fixtures/initcontainer/output-k8s.yaml' expected_warning: ''
PASS: converted output matches
PASS: warning found: ''
```

2024-03-21 12:11 UTC, cdrage requested changes
Sorry for the delay!

Some feedback:
- contaners is spelt wrong
- To match all the other labels, it should be `kompose.init.container.name` and `kompose.init.container.image` and `kompose.init.container.command`.

Good addition! Again, apologizes for the delay.

2024-03-21 12:12 UTC, cdrage requested changes

2024-03-21 12:12 UTC, cdrage commented on pkg/loader/compose/utils.go
> +	LabelInitContainerComand = "kompose.init-contaners.command"
LabelInitContainerComand should be spelled LabelInitContainerCommand

2024-03-23 17:01 UTC, sosan commented
> Sorry for the delay!
> 
> Some feedback:
> 
> * contaners is spelt wrong
> * To match all the other labels, it should be `kompose.init.container.name` and `kompose.init.container.image` and `kompose.init.container.command`.
> 
> Good addition! Again, apologizes for the delay.

changed labels to kompose.init.container.name, kompose.init.container.image, kompose.init.container.command
fixed documentation, tests and e2e
also merged main with new commits to this branch

2024-04-02 12:07 UTC, cdrage approved these changes

2024-04-02 12:07 UTC, cdrage commented
/lgtm

2024-04-08 12:49 UTC, merged