Feature 1635 - added labels to generate HPA
kubernetes/kompose pull request #1847
Opened 2024-03-26 20:12 UTC by sosan

#### What type of PR is this?

/kind feature 

#### What this PR does / why we need it:
added this labels to min/max replicas and custom metrics for cpu and memory:

kompose.hpa.minreplicas
kompose.hpa.maxreplicas
kompose.hpa.cpu
kompose.hpa.memory

documentated labels user_guide.md

generate custom metrics from cpu, memory and set min/max replicas

#### Which issue(s) this PR fixes:

Fixes #1631

#### Special notes for your reviewer:

2024-04-02 12:14 UTC, cdrage requested changes
This is amazing work, great job on the implementation!

Needs e2e and regular tests though, sorry!

2024-04-02 12:14 UTC, cdrage commented on docs/user-guide.md
> +version: '3.8'
needs to remove version

2024-04-02 12:14 UTC, cdrage commented on docs/user-guide.md
> +version: '3.8'
needs to remove version

2024-04-02 12:14 UTC, cdrage commented on docs/user-guide.md
> +version: '3.8'
needs to remove version

2024-04-02 12:14 UTC, cdrage commented on docs/user-guide.md
> +version: '3.8'
needs to remove version

2024-04-02 12:14 UTC, cdrage commented on docs/user-guide.md
> +| kompose.hpa.maxreplicas                             | defines Horizontal Pod Autoscaler max pod replicas                                   |
we need to follow how we do the other labels.

this should be instead: `kompose.hpa.replicas.min` and `kompose.hpa.replicas.max`

2024-04-03 20:44 UTC, TessaIO reviewed
Thanks @sosan for this amazing enhancement. I left a review, and I'll do another round when you finish this!

2024-04-04 18:41 UTC, sosan commented
done :ok_hand:

2024-04-10 11:43 UTC, sosan commented
fixed merge conflicts

2024-04-19 12:21 UTC, cdrage approved these changes
Amazing, thanks for the awesome work! All the code LGTM!

2024-04-19 12:21 UTC, cdrage commented
/lgtm

2024-04-19 12:21 UTC, cdrage commented
/approve

2024-04-19 12:24 UTC, merged