feat(deploy): support ephemeral storage requests limits labels
kubernetes/kompose pull request #1936
Opened 2024-09-27 00:14 UTC by jvitor83

#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Allow to use labels in the deploy section to convert to kubernetes resources requests and limits for ephemeral-storage

#### Which issue(s) this PR fixes:
Fixes #1935

#### Special notes for your reviewer:
❤️

2024-10-01 19:05 UTC, cdrage requested changes
Great implementation and it works! Thank you so much. 

We should follow the label convention (suggested in a comment).

Also are you able to write a test for k8sutils.go for the new functionality?

2024-10-01 19:05 UTC, cdrage commented on pkg/transformer/kubernetes/k8sutils.go
> +	if service.MemLimit != 0 || service.CPULimit != 0 || service.DeployLabels["limits.ephemeral-storage"] != "" {
We should follow https://kompose.io/user-guide/#labels convention.

Maybe instead let's do `kompose.ephemeral-storage.limit` and `kompose.ephemeral-storage.request` 

?

2024-10-03 23:08 UTC, jvitor83 commented
Changed and Added tests as asked @cdrage

2024-10-30 14:30 UTC, cdrage commented
So sorry for the delay, but thank you for the changes, this LGTM.

2024-10-30 14:31 UTC, cdrage approved these changes

2024-10-30 14:31 UTC, cdrage commented
/lgtm

2024-10-30 14:31 UTC, cdrage commented
/approve

2024-10-30 14:31 UTC, cdrage commented
Amazing work, big thanks for this new feature!!! 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀

2024-10-31 00:06 UTC, jvitor83 commented
Fixed the expected label in test, sorry, forgot to rename there before.
All good now @cdrage

2024-11-27 19:52 UTC, cdrage commented
/lgtm

2024-11-27 19:58 UTC, merged